### ISSUE TITLE
Exception is not thrown if nested in a function call with conditiona handled value

### ISSUE THREAD

**Issue by thaibault** [jandob/rebash#1]
Test to reproduce:

```bash
>>> exceptions.activate
>>> exceptions_foo() {
>>>     exceptions.try {
>>>         false
>>>     } exceptions.catch {
>>>         echo caught
>>>     }
>>>     echo should not be printed
>>> }
>>> exceptions_foo || echo info
caught
```

**Comment by jandob** [comment]
change to working test

**Comment by jandob** [comment]
Unfortunately the `||` disables `set -e` as well as `trap '' ERR` for the context inside `exceptions_foo`. 
I added a warning that is emitted in this case.
Also refer to https://groups.google.com/forum/?fromgroups=#!topic/gnu.bash.bug/NCK_0GmIv2M
