### ISSUE TITLE
Please add a LICENSE file with a chosen license

### ISSUE THREAD

**Issue by rawiriblundell** [jandob/rebash#3]
Hi,
I'd like to reference some of your code but without a clearly defined license, it defaults to standard copyright law, which is messy and restrictive.  Can you please choose a license and place an appropriate LICENSE file in your project root?

If you're unsure about which license to choose, this site might help: https://choosealicense.com/

Thanks in advance!

**Comment by jandob** [comment]
Sure thing, added a MIT LICENSE.
